.TH PGSNAP "1" "Sep 2012" "pgsnap 0.8.0" "User Commands"
.SH NAME
pgsnap \- PostgreSQL report tool
.SH DESCRIPTION
pgsnap is a PostgreSQL tool that mimics orasnap performance report tool for Oracle.
.SS "Usage:"
.IP
\&./pgsnap [OPTIONS]... [DBNAME]
.SS "General options:"
.TP
\fB\-a, \-\-all\fR
build a report for all databases on the PostgreSQL server
.TP
\fB\-d\fR DBNAME
specify database name to connect to
(default: your login name)
.TP
\fB\-\-delete\-if\-exists\fR
delete output directory if it already exists
.TP
\fB\-o\fR outputdir
specify output directory
specify output directory
(with -a, defaults to the current working directory; without -a, defaults to: "")
.TP
\fB\-\-output-dir-mode\fR outputdirmode
specify output directory permissions mode (default: "700")
.TP
\fB\-\-query\-in\-logs\fR
allow logging queries in PostgreSQL log files
.TP
\fB\-\-with\-old\-libpq\fR
disable the use of the parameter application_name
.TP
\fB\-S, \-\-without\-sysobjects\fR
all reports will display informations on user objects only
.TP
\fB\-?, \-\-help\fR
show this help, then exit
.TP
\fB\-v, \-\-version\fR
output version information, then exit
.SS "Connection options:"
.TP
\fB\-h\fR HOSTNAME
database server host or socket directory
(default: "localhost")
.TP
\fB\-p\fR PORT
database server port (default: "5432")
.TP
\fB\-U\fR NAME
database user name (default: your login name)
.TP
\fB\-W\fR
prompt for password
.TP
\fB\-w\fR
don't prompt for password

.SH AUTHOR and CREDITS
pgsnap is written and maintained by Guillaume Lelarge
.nh
<guillaume at lelarge dot info>
.PP
The pgsnap website:
.nh
.B http://pgsnap.projects.postgresql.org/
.hy
.PP
This manpage was written by Pierre Chifflier
.nh
<chifflier@debian.org>
and updated by Guillaume Lelarge
.nh
<guillaume at lelarge dot info>